[package]
name = "v1bectl_state"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core device state types for v1bectl"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
